services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=activity_db
    ports:
      - "5432:5432"
      
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/activity_db
      - DEBUG=TRUE
      - SECRET_KEY=demo
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CONSTANCE_REDIS_DB=1
    depends_on:
      - db
      - redis
  
  celery:
    build: .
    command: celery -A activity_logger worker -l info -Q activities
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/activity_db
      - DEBUG=TRUE
      - SECRET_KEY=demo
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CONSTANCE_REDIS_DB=1
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A activity_logger beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/activity_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CONSTANCE_REDIS_DB=1

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - web

  metrics:
    build: .
    command: python start_metrics.py
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/activity_db
      - DEBUG=TRUE
      - SECRET_KEY=demo
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CONSTANCE_REDIS_DB=1
    depends_on:
      - redis

volumes:
  postgres_data: