global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['web:8000']
    metrics_path: '/metrics'
  
  - job_name: 'celery'
    static_configs:
      - targets: ['metrics:8001']
    metrics_path: '/metrics'
