# Generated by Django 4.2.10 on 2025-04-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('run', 'Running'), ('walk', 'Walking'), ('cycle', 'Cycling'), ('swim', 'Swimming'), ('yoga', 'Yoga')], help_text='Select the activity performed', max_length=10, verbose_name='Type of Activity')),
                ('duration_minutes', models.PositiveIntegerField(help_text='How long the activity lasted, in minutes', verbose_name='Duration (minutes)')),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Your weight in kilograms (used for calorie calculations)', max_digits=5, verbose_name='Weight (kg)')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this activity', null=True, verbose_name='Optional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Logged At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10, verbose_name='Processing Status')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the processing was finished', null=True, verbose_name='Processed At')),
                ('calories_burned', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated calories burned during this activity', max_digits=7, null=True, verbose_name='Calories Burned')),
                ('celery_task_id', models.CharField(blank=True, editable=False, help_text='ID of task processing this activity.', max_length=255, null=True, verbose_name='Celery Task ID')),
                ('error_message', models.TextField(blank=True, help_text='Details about any errors if processing has failed', null=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
