# Generated by Django 4.2.10 on 2025-05-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Config Change Log',
                'verbose_name_plural': 'Config Change Logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
